# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centros',
            fields=[
                ('codigo_centro', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('nombre_centro', models.CharField(blank=True, max_length=120, null=True)),
                ('codigo_localidad', models.CharField(blank=True, max_length=10, null=True)),
                ('tipo_centro', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'centros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DificilDesempeno',
            fields=[
                ('codigo_centro', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dificil_desempeno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ensenanzas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_centro', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_ensenanza', models.CharField(blank=True, max_length=150, null=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ensenanzas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especialidades',
            fields=[
                ('especialidad', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('idioma', models.TextField(blank=True, null=True)),
                ('tiempo_parcial', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especialidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gaseosa',
            fields=[
                ('dni', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('cuota', models.CharField(blank=True, max_length=10, null=True)),
                ('apellido_1', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_2', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre', models.CharField(blank=True, max_length=60, null=True)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=6, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('provincia', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('tlf_casa', models.CharField(blank=True, max_length=18, null=True)),
                ('tlf_movil', models.CharField(blank=True, max_length=18, null=True)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('cuerpo', models.CharField(blank=True, max_length=5, null=True)),
                ('cod_centro_def', models.CharField(blank=True, max_length=12, null=True)),
                ('cod_centro_actual', models.CharField(blank=True, max_length=12, null=True)),
                ('auxiliar', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'db_table': 'gaseosa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Localidades',
            fields=[
                ('codigo_localidad', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_provincia', models.CharField(blank=True, max_length=20, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'localidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nombramientos',
            fields=[
                ('id', models.IntegerField(blank=True)),
                ('nif', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('nombre_completo', models.TextField(blank=True, null=True)),
                ('codigo_centro', models.TextField(blank=True, null=True)),
                ('procedimiento', models.TextField(blank=True, null=True)),
                ('fecha_procedimiento', models.DateField()),
                ('fecha_inicio', models.TextField(blank=True, null=True)),
                ('fecha_fin', models.TextField(blank=True, null=True)),
                ('especialidad', models.TextField(blank=True, null=True)),
                ('auxiliar', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nombramientos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('nombre_provincia', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'provincias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(blank=True, max_length=30, null=True)),
                ('destino', models.CharField(blank=True, max_length=30, null=True)),
                ('distancia', models.FloatField(blank=True, null=True)),
                ('minutos', models.FloatField(blank=True, null=True)),
                ('sumario', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rutas',
                'managed': False,
            },
        ),
    ]
