# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionweb', '0002_auto_20160117_1750'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='dificildesempeno',
            table='dificil_desempeno',
        ),
    ]
