# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionweb', '0004_auto_20160118_1046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='centros',
            options={'managed': False, 'ordering': ['nombre_centro']},
        ),
        migrations.AlterModelOptions(
            name='gaseosa',
            options={'managed': False, 'ordering': ['apellido_1', 'apellido_2']},
        ),
    ]
