# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionweb', '0006_centrosregion_correspondencias_ensenanzasregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('codigo_localidad', models.CharField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('nombre_localidad', models.CharField(blank=True, max_length=100, null=True)),
                ('nombre_provincia', models.CharField(blank=True, max_length=20, null=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'localidades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nombramiento',
            fields=[
                ('id', models.IntegerField(blank=True, null=True)),
                ('nif', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('nombre_completo', models.TextField(blank=True, null=True)),
                ('procedimiento', models.TextField(blank=True, null=True)),
                ('fecha_procedimiento', models.DateField()),
                ('fecha_inicio', models.TextField(blank=True, null=True)),
                ('fecha_fin', models.TextField(blank=True, null=True)),
                ('especialidad', models.TextField(blank=True, null=True)),
                ('auxiliar', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nombramientos',
                'managed': False,
            },
        ),
    ]
