# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 08:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMensajeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=4096)),
            ],
        ),
        migrations.CreateModel(
            name='MensajePendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil_usuario', models.CharField(max_length=15, verbose_name='Tlf_Movil')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmensajeria.Mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaMensajeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_sistema', models.CharField(max_length=50, verbose_name='Sistema')),
            ],
        ),
        migrations.CreateModel(
            name='SuscripcionSistemaMensajeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil_usuario', models.CharField(max_length=15, verbose_name='Tlf_Movil')),
                ('sistema_mensajeria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmensajeria.SistemaMensajeria')),
            ],
        ),
    ]
