# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-23 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionmensajeria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeBienEnviado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil_usuario', models.CharField(max_length=15, verbose_name='Tlf_Movil')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmensajeria.Mensaje')),
            ],
        ),
        migrations.CreateModel(
            name='MensajeMalEnviado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movil_usuario', models.CharField(max_length=15, verbose_name='Tlf_Movil')),
                ('mensaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionmensajeria.Mensaje')),
            ],
        ),
    ]
