# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionmensajeria', '0002_mensajebienenviado_mensajemalenviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='sistema_a_usar',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gestionmensajeria.SistemaMensajeria'),
            preserve_default=False,
        ),
    ]
