
Public Function ActualizarConcursilloEEMM2015()
On Error Resume Next

  Dim ws As Workspace
  Dim db As Database
  Dim strSQL As String

  Set ws = DBEngine.Workspaces(0)
  Set db = ws.Databases(0)

On Error GoTo Proc_Err
  'start a transaction to ensure all updates are run or rolled back
  ws.BeginTrans
  
71215575P:Badillo Martinez, Antonia:PEND. DESTINO:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR
05645549S:Lazaro Espadas, Alfonso:DENEGADO:13004122:EA ANTONIO LÓPEZ:TOMELLOSO:CIUDAD REAL:13004122:EA ANTONIO LÓPEZ:EA ANTONIO LÓPEZ:CIUDAD REAL
04153226R:Moreno Del Pino, Javier:PEND. DESTINO:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR
33482906N:Pascual Noguerol, Maria Amparo:DENEGADO:13004122:EA ANTONIO LÓPEZ:TOMELLOSO:CIUDAD REAL:13004122:EA ANTONIO LÓPEZ:EA ANTONIO LÓPEZ:CIUDAD REAL
03901846B:Sanchez Tejeda, Rodrigo:PEND. DESTINO:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR
04195638R:Valero Jimenez, Jose Carlos:PEND. DESTINO:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR
45432358K:Velasco Suarez, Pedro:PEND. DESTINO:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR:NO TENIA DEST. ANTERIOR
18029748W:Velduque Ballarin, Maria Jesus:DENEGADO:16008667:EA JOSÉ MARÍA CRUZ NOVILLO:CUENCA:CUENCA:16008667:EA JOSÉ MARÍA CRUZ NOVILLO:EA JOSÉ MARÍA CRUZ NOVILLO:CUENCA

ws.CommitTrans

Proc_Exit:
  Set ws = Nothing
  Set db = Nothing
  Exit Function

Proc_Err:
  ws.Rollback
  MsgBox "Error updating: " & Err.Description
  Resume Proc_Exit
End Sub

