# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-31 13:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grafo', '0002_poblacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('codigo', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
            ],
        ),
    ]
