insert or ignore into localidades values ('02003000', 'Albacete                     Aguas Nuevas                - Diseño y Amueblamiento.                               Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Aguas Nuevas           - Educación Secundaria Obligatoria.                     Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Bachillerato de Ciencias y Tecnología.                Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Bachillerato de Ciencias y Tecnología.                Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Bachillerato de Ciencias y Tecnología.                Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Animación Socio-Cultural (Grado Superior).            Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Aceites de Oliva y Vinos.                          Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Automatización y Robótica Industrial.              Vespertino', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Bachillerato de Ciencias y Tecnología.              Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Arreglo y Reparación de Artículos Textiles y de Piel.   Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Administración de Sistemas Informáticos En Red.    Vespertino', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Animación de Actividades Físicas y Deportivas      Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Bachillerato de Ciencias y Tecnología.                 Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Actividades Comerciales.                           Diurno', 'Albacete');
insert or ignore into localidades values ('02003000', 'Albacete               Albacete               - Educación Secundaria Obligatoria.                     Diurno', 'Albacete');
insert or ignore into localidades values ('02008000', 'Alcaraz                Alcaraz                - Bachillerato de Ciencias y Tecnología.                Diurno', 'Albacete');
insert or ignore into localidades values ('02009000', 'Almansa                Almansa                - Atención A Personas En Situación de Dependencia.      Vespertino', 'Albacete');
insert or ignore into localidades values ('02009000', 'Almansa               Almansa               - Administración y Finanzas.                          Diurno', 'Albacete');
insert or ignore into localidades values ('02009000', 'Almansa               Almansa               - Automatización y Robótica Industrial.               Diurno', 'Albacete');
insert or ignore into localidades values ('02010000', 'Alpera                 Alpera                 - Educación Secundaria Obligatoria.                  Diurno', 'Albacete');
insert or ignore into localidades values ('02012000', 'Balazote               Balazote               - Educación Secundaria Obligatoria.                  Diurno', 'Albacete');
insert or ignore into localidades values ('02019000', 'Bonillo (El)           Bonillo (El)           - Bachillerato de Ciencias y Tecnología.             Diurno', 'Albacete');
insert or ignore into localidades values ('02024000', 'Casas-Ibáñez           Casas-Ibañez           - Administración y Finanzas.                         Diurno', 'Albacete');
insert or ignore into localidades values ('02025000', 'Caudete                    Caudete                      - Atención A Personas En Situación de Dependencia.   Diurno', 'Albacete');
insert or ignore into localidades values ('02029000', 'Chinchilla de Monte-Aragón Chinchilla de Monte-Aragon   - Educación Secundaria Obligatoria.                  Diurno', 'Albacete');
insert or ignore into localidades values ('02030000', 'Elche de la Sierra         Elche de la Sierra           - Aprovechamientos Forestales.                       Diurno', 'Albacete');
insert or ignore into localidades values ('02033000', 'Fuente-Álamo         Fuente-Alamo         - Bachillerato de Ciencias y Tecnología.             Diurno', 'Albacete');
insert or ignore into localidades values ('02037000', 'Hellín               Hellin               - Administración de Sistemas Informáticos En Red.    Diurno', 'Albacete');
insert or ignore into localidades values ('02037000', 'Hellín               Hellin               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Albacete');
insert or ignore into localidades values ('02037000', 'Hellín               Hellin               - Bachillerato de Ciencias y Tecnología.                  Diurno', 'Albacete');
insert or ignore into localidades values ('02037000', 'Hellín               Hellin               - Arreglo y Reparación de Artículos Textiles y de Piel.   Diurno', 'Albacete');
insert or ignore into localidades values ('02045000', 'Madrigueras          Madrigueras          - Atención A Personas En Situación de Dependencia.        Diurno', 'Albacete');
insert or ignore into localidades values ('02053000', 'Munera               Munera               - Educación Secundaria Obligatoria.                  Diurno', 'Albacete');
insert or ignore into localidades values ('02055000', 'Nerpio               Nerpio               - Educación Secundaria Obligatoria.                  Diurno', 'Albacete');
insert or ignore into localidades values ('02057000', 'Ossa de Montiel      Ossa de Montiel      - Educación Secundaria Obligatoria.                  Diurno', 'Albacete');
insert or ignore into localidades values ('02901000', 'Pozo Cañada          Pozo Cañada          - Educación Secundaria Obligatoria.                  Diurno', 'Albacete');
insert or ignore into localidades values ('02067000', 'Riópar               Riopar               - Educación Secundaria Obligatoria.                  Diurno', 'Albacete');
insert or ignore into localidades values ('02069000', 'Roda (La)            Roda (La)            - Bachillerato de Ciencias y Tecnología.             Diurno', 'Albacete');
insert or ignore into localidades values ('02069000', 'Roda (La)            Roda (La)            - Administración y Finanzas.                         Diurno', 'Albacete');
insert or ignore into localidades values ('02072000', 'Socovos                 Socovos                 - Educación Secundaria Obligatoria.                  Diurno', 'Albacete');
insert or ignore into localidades values ('02073000', 'Tarazona de la Mancha   Tarazona de la Mancha   - Bachillerato de Ciencias y Tecnología.             Diurno', 'Albacete');
insert or ignore into localidades values ('02074000', 'Tobarra                 Tobarra                 - Bachillerato de Ciencias y Tecnología.             Diurno', 'Albacete');
insert or ignore into localidades values ('02079000', 'Villamalea              Villamalea              - Educación Secundaria Obligatoria.                  Diurno', 'Albacete');
insert or ignore into localidades values ('02081000', 'Villarrobledo        Villarrobledo        - Bachillerato de Ciencias y Tecnología.              Diurno', 'Albacete');
insert or ignore into localidades values ('02081000', 'Villarrobledo        Villarrobledo        - Administración y Finanzas.                          Diurno', 'Albacete');
insert or ignore into localidades values ('02081000', 'Villarrobledo        Villarrobledo        - Bachillerato de Artes Plásticas, Imagen y Diseño.   Diurno', 'Albacete');
insert or ignore into localidades values ('02086001', 'Yeste               Yeste               - Bachillerato de Ciencias y Tecnología.              Diurno', 'Albacete');
insert or ignore into localidades values ('13005000', 'Alcázar de San Juan   Alcazar de San Juan   - Bachillerato de Ciencias y Tecnología.                Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13005000', 'Alcázar de San Juan   Alcazar de San Juan   - Actividades Comerciales.                              Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13005000', 'Alcázar de San Juan   Alcazar de San Juan   - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13011000', 'Almadén               Almaden               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13011000', 'Almadén               Almaden               - Administración y Finanzas.                         Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13013000', 'Almagro               Almagro               - Administración y Finanzas.                            Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13013000', 'Almagro               Almagro               - Bachillerato de Ciencias y Tecnología.                Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13015000', 'Almodóvar del Campo        Almodovar del Campo        - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13019000', 'Argamasilla de Alba        Argamasilla de Alba        - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13020000', 'Argamasilla de Calatrava   Argamasilla de Calatrava   - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13023000', 'Bolaños de Calatrava       Bolaños de Calatrava       - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13027000', 'Calzada de Calatrava       Calzada de Calatrava       - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13028000', 'Campo de Criptana   Campo de Criptana   - Bachillerato de Artes Escénicas, Música y Danza.      Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13034000', 'Ciudad Real         Ciudad Real         - Actividades Comerciales.                              Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13034000', 'Ciudad Real         Ciudad Real         - Bachillerato de Ciencias y Tecnología.           Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13034000', 'Ciudad Real         Ciudad Real         - Agencias de Viajes y Gestión de Eventos.              Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13034000', 'Ciudad Real         Ciudad Real         - Animación de Actividades Físicas y Deportivas         Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13034000', 'Ciudad Real         Ciudad Real         - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13034000', 'Ciudad Real           Ciudad Real           - Atención A Personas En Situación de Dependencia.   Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13039000', 'Daimiel               Daimiel               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13039000', 'Daimiel               Daimiel               - Administración y Finanzas.                         Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13042000', 'Fuencaliente            Fuencaliente            - Educación Secundaria Obligatoria.                  Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13047000', 'Herencia                Herencia                - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13049000', 'Horcajo de los Montes   Horcajo de los Montes   - Educación Secundaria Obligatoria.                  Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13052000', 'Malagón                 Malagon                 - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13053000', 'Manzanares         Manzanares         - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13053000', 'Manzanares         Manzanares         - Administración y Finanzas.                         Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13054000', 'Membrilla            Membrilla            - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13056000', 'Miguelturra          Miguelturra          - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13058000', 'Moral de Calatrava   Moral de Calatrava   - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13061000', 'Pedro Muñoz          Pedro Muñoz          - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13063000', 'Piedrabuena          Piedrabuena          - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13065000', 'Porzuna               Porzuna               - Aprovechamiento y Conservación del Medio Natural.     Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13071000', 'Puertollano           Puertollano           - Bachillerato de Ciencias y Tecnología.                Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13071000', 'Puertollano           Puertollano           - Actividades Comerciales.                              Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13071000', 'Puertollano         Puertollano         - Animación Socio-Cultural (Grado Superior).             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13071000', 'Puertollano         Puertollano         - Automatización y Robótica Industrial.                  Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13071000', 'Puertollano            Puertollano            - Bachillerato de Ciencias y Tecnología.              Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13071000', 'Puertollano            Puertollano            - Bachillerato de Artes Plásticas, Imagen y Diseño.   Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13077000', 'Santa Cruz de Mudela   Santa Cruz de Mudela   - Bachillerato de Ciencias y Tecnología.              Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13078000', 'Socuéllamos            Socuellamos            - Administración y Finanzas.                          Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13079000', 'Solana (La)         Solana (La)         - Atención A Personas En Situación de Dependencia.   Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13079000', 'Solana (La)         Solana (La)         - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13082000', 'Tomelloso           Tomelloso           - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13082000', 'Tomelloso          Tomelloso          - Actividades Comerciales.                           Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13082000', 'Tomelloso          Tomelloso          - Bachillerato de Ciencias y Tecnología.              Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13082000', 'Tomelloso          Tomelloso          - Bachillerato de Ciencias y Tecnología.              Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13087000', 'Valdepeñas         Valdepeñas         - Bachillerato de Artes Plásticas, Imagen y Diseño.   Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13087000', 'Valdepeñas         Valdepeñas         - Aceites de Oliva y Vinos.                             Vespertino', 'Ciudad Real');
insert or ignore into localidades values ('13087000', 'Valdepeñas         Valdepeñas         - Bachillerato de Ciencias y Tecnología.            Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13092000', 'Villanueva de la Fuente      Villanueva de la Fuente      - Educación Secundaria Obligatoria.                  Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13093000', 'Villanueva de los Infantes   Villanueva de los Infantes   - Atención A Personas En Situación de Dependencia.   Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13093000', 'Villanueva de los Infantes   Villanueva de los Infantes   - Administración y Finanzas.                         Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13096000', 'Villarrubia de los Ojos      Villarrubia de los Ojos      - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('13098000', 'Viso del Marqués    Viso del Marques    - Bachillerato de Ciencias y Tecnología.             Diurno', 'Ciudad Real');
insert or ignore into localidades values ('16033000', 'Belmonte                  Belmonte                  - Bachillerato de Ciencias y Tecnología.                Diurno', 'Cuenca');
insert or ignore into localidades values ('16052000', 'Cañete                    Cañete                    - Educación Secundaria Obligatoria.                     Diurno', 'Cuenca');
insert or ignore into localidades values ('16055000', 'Carboneras de Guadazaón   Carboneras de Guadazaon   - Educación Secundaria Obligatoria.                     Diurno', 'Cuenca');
insert or ignore into localidades values ('16066000', 'Casasimarro               Casasimarro               - Educación Secundaria Obligatoria.                     Diurno', 'Cuenca');
insert or ignore into localidades values ('16078000', 'Cuenca                    Cuenca                    - Actividades Comerciales.                              Diurno', 'Cuenca');
insert or ignore into localidades values ('16078000', 'Cuenca               Cuenca               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Cuenca');
insert or ignore into localidades values ('16078000', 'Cuenca               Cuenca               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Cuenca');
insert or ignore into localidades values ('16078000', 'Cuenca               Cuenca               - Administración de Sistemas Informáticos En Red.       Vespertino', 'Cuenca');
insert or ignore into localidades values ('16078000', 'Cuenca               Cuenca               - Bachillerato de Ciencias y Tecnología.                Diurno', 'Cuenca');
insert or ignore into localidades values ('16078000', 'Cuenca                Cuenca                - Animación de Actividades Físicas y Deportivas       Diurno', 'Cuenca');
insert or ignore into localidades values ('16106000', 'Horcajo de Santiago   Horcajo de Santiago   - Bachillerato de Ciencias y Tecnología.              Diurno', 'Cuenca');
insert or ignore into localidades values ('16112000', 'Huete                 Huete                 - Educación Secundaria Obligatoria.                   Diurno', 'Cuenca');
insert or ignore into localidades values ('16113000', 'Iniesta               Iniesta               - Bachillerato de Ciencias y Tecnología.              Diurno', 'Cuenca');
insert or ignore into localidades values ('16117000', 'Landete               Landete               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Cuenca');
insert or ignore into localidades values ('16124000', 'Mesas (Las)           Mesas (Las)           - Educación Secundaria Obligatoria.                  Diurno', 'Cuenca');
insert or ignore into localidades values ('16125000', 'Minglanilla           Minglanilla           - Agro-Jardinería y Composiciones Florales.          Diurno', 'Cuenca');
insert or ignore into localidades values ('16133000', 'Mota del Cuervo       Mota del Cuervo       - Administración de Sistemas Informáticos En Red.    Diurno', 'Cuenca');
insert or ignore into localidades values ('16134000', 'Motilla del Palancar   Motilla del Palancar   - Administración y Finanzas.                         Diurno', 'Cuenca');
insert or ignore into localidades values ('16154000', 'Pedroñeras (Las)       Pedroñeras (Las)       - Actividades Comerciales.                           Diurno', 'Cuenca');
insert or ignore into localidades values ('16170000', 'Priego               Priego               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Cuenca');
insert or ignore into localidades values ('16171000', 'Provencio (El)       Provencio (El)       - Educación Secundaria Obligatoria.                  Diurno', 'Cuenca');
insert or ignore into localidades values ('16175000', 'Quintanar del Rey    Quintanar del Rey    - Atención A Personas En Situación de Dependencia.   Diurno', 'Cuenca');
insert or ignore into localidades values ('16190000', 'San Clemente         San Clemente         - Bachillerato de Ciencias y Tecnología.             Diurno', 'Cuenca');
insert or ignore into localidades values ('16198000', 'Sisante               Sisante               - Educación Secundaria Obligatoria.                  Diurno', 'Cuenca');
insert or ignore into localidades values ('16203000', 'Tarancón              Tarancon              - Administración y Finanzas.                         Diurno', 'Cuenca');
insert or ignore into localidades values ('16903000', 'Valeras (Las)         Valera de Abajo       - Bachillerato de Ciencias y Tecnología.             Diurno', 'Cuenca');
insert or ignore into localidades values ('16249000', 'Villamayor de Santiago   Villamayor de Santiago   - Educación Secundaria Obligatoria.                  Diurno', 'Cuenca');
insert or ignore into localidades values ('16251000', 'Villanueva de la Jara    Villanueva de la Jara    - Educación Secundaria Obligatoria.                  Diurno', 'Cuenca');
insert or ignore into localidades values ('16269000', 'Villares del Saz         Villares del Saz         - Bachillerato de Ciencias y Tecnología.             Diurno', 'Cuenca');
insert or ignore into localidades values ('19024000', 'Alovera               Alovera               - Agro-Jardinería y Composiciones Florales.          Diurno', 'Guadalajara');
insert or ignore into localidades values ('19046000', 'Azuqueca de Henares   Azuqueca de Henares   - Administración de Sistemas Informáticos En Red.    Diurno', 'Guadalajara');
insert or ignore into localidades values ('19046000', 'Azuqueca de Henares   Azuqueca de Henares   - Administración y Finanzas.                         Diurno', 'Guadalajara');
insert or ignore into localidades values ('19046000', 'Azuqueca de Henares    Azuqueca de Henares    - Bachillerato de Ciencias y Tecnología.             Diurno', 'Guadalajara');
insert or ignore into localidades values ('19053000', 'Brihuega               Brihuega               - Educación Secundaria Obligatoria.                  Diurno', 'Guadalajara');
insert or ignore into localidades values ('19058000', 'Cabanillas del Campo   Cabanillas del Campo   - Animación de Actividades Físicas y Deportivas       Diurno', 'Guadalajara');
insert or ignore into localidades values ('19071000', 'Casar (El)             Casar (El)             - Administración y Finanzas.                          Diurno', 'Guadalajara');
insert or ignore into localidades values ('19071000', 'Casar (El)             Casar (El)             - Bachillerato de Ciencias y Tecnología.              Diurno', 'Guadalajara');
insert or ignore into localidades values ('19105000', 'Chiloeches             Chiloeches             - Bachillerato de Ciencias y Tecnología.              Diurno', 'Guadalajara');
insert or ignore into localidades values ('19086000', 'Cifuentes           Cifuentes           - Bachillerato de Ciencias y Tecnología.                Diurno', 'Guadalajara');
insert or ignore into localidades values ('19130000', 'Guadalajara         Guadalajara         - Actividades Comerciales.                              Diurno', 'Guadalajara');
insert or ignore into localidades values ('19130000', 'Guadalajara         Guadalajara         - Automatización y Robótica Industrial.              Diurno', 'Guadalajara');
insert or ignore into localidades values ('19130000', 'Guadalajara         Guadalajara         - Agencias de Viajes y Gestión de Eventos.           Diurno', 'Guadalajara');
insert or ignore into localidades values ('19130000', 'Guadalajara         Guadalajara         - Bachillerato de Ciencias y Tecnología.             Diurno', 'Guadalajara');
insert or ignore into localidades values ('19130000', 'Guadalajara         Guadalajara         - Bachillerato de Ciencias y Tecnología.              Diurno', 'Guadalajara');
insert or ignore into localidades values ('19130000', 'Guadalajara         Guadalajara         - Agro-Jardinería y Composiciones Florales.           Diurno', 'Guadalajara');
insert or ignore into localidades values ('19130000', 'Guadalajara         Guadalajara         - Automoción.                                        Vespertino', 'Guadalajara');
insert or ignore into localidades values ('19156000', 'Jadraque            Jadraque            - Educación Secundaria Obligatoria.                  Diurno', 'Guadalajara');
insert or ignore into localidades values ('19171000', 'Marchamalo             Marchamalo             - Bachillerato de Ciencias y Tecnología.             Diurno', 'Guadalajara');
insert or ignore into localidades values ('19190000', 'Molina de Aragón       Molina                 - Bachillerato de Ciencias y Tecnología.             Diurno', 'Guadalajara');
insert or ignore into localidades values ('19192000', 'Mondéjar               Mondejar               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Guadalajara');
insert or ignore into localidades values ('19212000', 'Pastrana               Pastrana               - Atención A Personas En Situación de Dependencia.   Vespertino', 'Guadalajara');
insert or ignore into localidades values ('19245000', 'Sacedón                  Sacedon                  - Educación Secundaria Obligatoria.                  Diurno', 'Guadalajara');
insert or ignore into localidades values ('19257002', 'Sigüenza                 Siguenza                 - Bachillerato de Ciencias y Tecnología.             Diurno', 'Guadalajara');
insert or ignore into localidades values ('19319000', 'Villanueva de la Torre   Villanueva de la Torre   - Bachillerato de Ciencias y Tecnología.             Diurno', 'Guadalajara');
insert or ignore into localidades values ('19331000', 'Yunquera de Henares      Yunquera de Henares      - Agro-Jardinería y Composiciones Florales.          Diurno', 'Guadalajara');
insert or ignore into localidades values ('45014000', 'Añover de Tajo        Añover de Tajo        - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45019000', 'Bargas                Bargas                - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45020000', 'Belvis de la Jara     Belvis de la Jara     - Educación Secundaria Obligatoria.                  Diurno', 'Toledo');
insert or ignore into localidades values ('45031000', 'Camarena              Camarena              - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45038000', 'Carranque             Carranque             - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45046000', 'Cebolla               Cebolla               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45053000', 'Consuegra            Consuegra            - Administración y Finanzas.                         Diurno', 'Toledo');
insert or ignore into localidades values ('45054000', 'Corral de Almaguer   Corral de Almaguer   - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45061000', 'Escalona            Escalona            - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45064000', 'Esquivias           Esquivias           - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45066000', 'Fuensalida          Fuensalida          - Actividades Comerciales.                           Diurno', 'Toledo');
insert or ignore into localidades values ('45067000', 'Gálvez                 Galvez                 - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45081000', 'Illescas               Illescas               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45081000', 'Illescas               Illescas               - Actividades Comerciales.                           Diurno', 'Toledo');
insert or ignore into localidades values ('45087000', 'Madridejos             Madridejos             - Administración de Sistemas Informáticos En Red.    Diurno', 'Toledo');
insert or ignore into localidades values ('45099000', 'Méntrida               Mentrida               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45101000', 'Miguel Esteban         Miguel Esteban         - Educación Secundaria Obligatoria.                  Diurno', 'Toledo');
insert or ignore into localidades values ('45106000', 'Mora                   Mora                   - Aceites de Oliva y Vinos.                          Diurno', 'Toledo');
insert or ignore into localidades values ('45109000', 'Navahermosa            Navahermosa            - Educación Secundaria Obligatoria.                  Diurno', 'Toledo');
insert or ignore into localidades values ('45112000', 'Navalmorales (Los)     Navalmorales (Los)     - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45119000', 'Numancia de la Sagra   Numancia de la Sagra   - Agro-Jardinería y Composiciones Florales.          Diurno', 'Toledo');
insert or ignore into localidades values ('45121000', 'Ocaña               Ocaña               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45121000', 'Ocaña               Ocaña               - Administración y Finanzas.                         Diurno', 'Toledo');
insert or ignore into localidades values ('45125000', 'Oropesa                     Oropesa                     - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45135000', 'Puebla de Almoradiel (La)   Puebla de Almoradiel (La)   - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45136000', 'Puebla de Montalbán (La)    Puebla de Montalban (La)    - Administración y Finanzas.                         Diurno', 'Toledo');
insert or ignore into localidades values ('45142000', 'Quintanar de la Orden   Quintanar de la Orden   - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45142000', 'Quintanar de la Orden   Quintanar de la Orden   - Administración y Finanzas.                         Diurno', 'Toledo');
insert or ignore into localidades values ('45145000', 'Recas                    Recas                    - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45156000', 'Santa Cruz de la Zarza   Santa Cruz de la Zarza   - Educación Secundaria Obligatoria.                  Diurno', 'Toledo');
insert or ignore into localidades values ('45161000', 'Seseña                   Seseña                   - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45161000', 'Seseña                   Seseña                   - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45163000', 'Sonseca                  Sonseca                  - Administración y Finanzas.                         Diurno', 'Toledo');
insert or ignore into localidades values ('45165000', 'Talavera de la Reina   Talavera de la Reina   - Bachillerato de Ciencias y Tecnología.                  Diurno', 'Toledo');
insert or ignore into localidades values ('45165000', 'Talavera de la Reina   Talavera de la Reina   - Arreglo y Reparación de Artículos Textiles y de Piel.   Diurno', 'Toledo');
insert or ignore into localidades values ('45165000', 'Talavera de la Reina   Talavera de la Reina   - Agro-Jardinería y Composiciones Florales.         Diurno', 'Toledo');
insert or ignore into localidades values ('45165000', 'Talavera de la Reina   Talavera de la Reina   - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45165000', 'Talavera de la Reina   Talavera de la Reina   - Actividades Comerciales.                           Diurno', 'Toledo');
insert or ignore into localidades values ('45165000', 'Talavera de la Reina   Talavera de la Reina   - Administración de Sistemas Informáticos En Red.     Diurno', 'Toledo');
insert or ignore into localidades values ('45168000', 'Toledo               Toledo               - Administración y Finanzas.                         Distancia', 'Toledo');
insert or ignore into localidades values ('45168000', 'Toledo               Toledo               - Animación Sociocultural y Turística.                Diurno', 'Toledo');
insert or ignore into localidades values ('45168000', 'Toledo               Toledo               - Administración de Sistemas Informáticos En Red.       Vespertino', 'Toledo');
insert or ignore into localidades values ('45168000', 'Toledo               Toledo               - Actividades Comerciales.                              Diurno', 'Toledo');
insert or ignore into localidades values ('45168000', 'Toledo               Toledo               - Asesoría de Imagen Personal (Grado Superior).      Vespertino', 'Toledo');
insert or ignore into localidades values ('45168000', 'Toledo               Toledo               - Bachillerato de Ciencias y Tecnología.                 Diurno', 'Toledo');
insert or ignore into localidades values ('45168000', 'Toledo               Toledo               - Bachillerato de Ciencias y Tecnología.                 Diurno', 'Toledo');
insert or ignore into localidades values ('45168000', 'Toledo                 Toledo                 - Animación de Actividades Físicas y Deportivas      Diurno', 'Toledo');
insert or ignore into localidades values ('45168000', 'Toledo                 Toledo                 - Educación Secundaria Obligatoria.                  Diurno', 'Toledo');
insert or ignore into localidades values ('45173000', 'Torrijos               Torrijos               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45173000', 'Torrijos               Torrijos               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45180000', 'Valmojado                    Valmojado                    - Atención A Personas En Situación de Dependencia.   Diurno', 'Toledo');
insert or ignore into localidades values ('45186000', 'Villa de Don Fadrique (La)   Villa de Don Fadrique (La)   - Educación Secundaria Obligatoria.                  Diurno', 'Toledo');
insert or ignore into localidades values ('45185000', 'Villacañas                   Villacañas                   - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45185000', 'Villacañas                   Villacañas                   - Administración y Finanzas.                         Diurno', 'Toledo');
insert or ignore into localidades values ('45187000', 'Villafranca de los Caballeros Villafranca de los Caballeros   - Educación Secundaria Obligatoria.                   Diurno', 'Toledo');
insert or ignore into localidades values ('45188000', 'Villaluenga de la Sagra       Villaluenga de la Sagra         - Bachillerato de Ciencias y Tecnología.              Diurno', 'Toledo');
insert or ignore into localidades values ('45200000', 'Yébenes (Los)                 Yebenes (Los)                   - Aprovechamiento y Conservación del Medio Natural.   Diurno', 'Toledo');
insert or ignore into localidades values ('45202000', 'Yepes                Yepes                - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
insert or ignore into localidades values ('45205000', 'Yuncos               Yuncos               - Bachillerato de Ciencias y Tecnología.             Diurno', 'Toledo');
