# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestioncursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='descripcion',
            field=models.CharField(max_length=150),
        ),
    ]
